name: CI

on:
    push:
        branches:
            - main # Измените на нужные ветки

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                service: [api-gateway, heating-service, device-service] # Добавьте или измените сервисы по необходимости

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-${{ matrix.service }}-

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v6
              with:
                  context: ./smart-home-microservices/${{ matrix.service }}
                  file: ./smart-home-microservices/${{ matrix.service }}/Dockerfile
                  push: true
                  tags: ghcr.io/yandex-practicum/architecture-sprint-3/${{ matrix.service }}:latest
                  platforms: linux/amd64,linux/arm64
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Verify Image Push
              run: |
                  echo "Successfully pushed ghcr.io/yandex-practicum/architecture-sprint-3/${{ matrix.service }}:latest"
